### ISSUE TITLE
Add multi-argument support to pybugger.custom()

### ISSUE THREAD

**Issue by fareskalaboud** [fareskalaboud/pybugger#1]
At the moment, it takes three arguments: the string, the foreground colour and the background colour. Is it possible to make it accept multiple string arguments (using the `*` notation, similar to other methods) while making it recognise/distinguish the foreground and background colors?

**Comment by damavrom** [comment]
Won't passing a list of strings work?

**Comment by theelous3** [comment]
Like in: https://github.com/fareskalaboud/pybugger/pull/2 ?

**Comment by fareskalaboud** [comment]
Yes! Apologies this took a while, thank you @theelous3
